"""
This type stub file was generated by pyright.
"""

import sys
from collections.abc import OrderedDict
from werkzeug.http import HTTP_STATUS_CODES

PY3 = ...
def http_status_message(code): # -> str:
    """Maps an HTTP status code to the textual status"""
    ...

def unpack(value): # -> tuple[Any, Literal[200], dict[Any, Any]] | tuple[Any, Any, Any] | tuple[Any, Any, dict[Any, Any]] | tuple[tuple[Any, ...], Literal[200], dict[Any, Any]]:
    """Return a three tuple of data, code, and headers"""
    ...

